/* tslint:disable */
/* eslint-disable */
/**
 * WE_HA1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost:3000".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: AxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
    "DefaultApi.deleteCategoriesFromRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.deleteCategory": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.deleteIngredient": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.deleteIngredientsFromRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.deleteRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.deleteStepsFromRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllCategory": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllIngredients": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllRecipeByAnIngredient": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllRecipeByCategories": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllRecipeByIngredients": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllRecipes": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getAllRecipesteps": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getCategory": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getIngredient": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getIngredientsFromRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getRecipeGtRating": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.getTagsFromRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.postCategory": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.postIngredient": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.postRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.putCategory": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.putIngredient": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
    "DefaultApi.putRecipe": [
        {
            url: "http://localhost:3000",
            description: "No description provided",
        }
    ],
}
